---
name: 'Build'

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build

      - name: HACS build validation
        uses: "hacs/action@22.5.0"
        with:
          category: "plugin"

          # Don't attempt to load into HACS (as it loads the release, not the
          # build).
          ignore: "hacs"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frigate-hass-card
          path: dist/frigate-hass-card.js
